/**
 * Build pipeline (esbuild):
 *  1. Bundle the web client (packages/renderer/web/app.ts) to a browser IIFE.
 *  2. Inline that JS + styles.css + index.html into a generated TS module
 *     (packages/renderer/src/assets.generated.ts) so the renderer ships its UI
 *     compiled-in with no runtime file lookups.
 *  3. Bundle the CLI (which pulls in core + renderer) to a single self-contained
 *     ESM file at packages/cli/dist/patchstory.mjs. Zero runtime npm deps.
 */

import { build } from "esbuild";
import { readFileSync, writeFileSync, mkdirSync, chmodSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const webDir = join(root, "packages/renderer/web");
const rendererSrc = join(root, "packages/renderer/src");
const cliDist = join(root, "packages/cli/dist");

async function bundleWebClient() {
  const result = await build({
    entryPoints: [join(webDir, "app.ts")],
    bundle: true,
    format: "iife",
    platform: "browser",
    target: ["es2020"],
    minify: true,
    legalComments: "none",
    write: false,
  });
  return result.outputFiles[0].text;
}

function generateAssetsModule(js, css, html) {
  const banner =
    "/* AUTO-GENERATED by build.mjs — do not edit. Run `npm run build`. */\n";
  const body =
    `export const WEB_JS = ${JSON.stringify(js)};\n` +
    `export const WEB_CSS = ${JSON.stringify(css)};\n` +
    `export const WEB_HTML = ${JSON.stringify(html)};\n`;
  writeFileSync(join(rendererSrc, "assets.generated.ts"), banner + body, "utf8");
}

async function bundleCli() {
  mkdirSync(cliDist, { recursive: true });
  const outfile = join(cliDist, "patchstory.mjs");
  const cliVersion = JSON.parse(
    readFileSync(join(root, "packages/cli/package.json"), "utf8"),
  ).version;
  await build({
    entryPoints: [join(root, "packages/cli/src/cli.ts")],
    bundle: true,
    format: "esm",
    platform: "node",
    target: ["node20"],
    outfile,
    legalComments: "none",
    // Inject the package version so `--version` always matches what's published.
    define: { __PATCHSTORY_VERSION__: JSON.stringify(cliVersion) },
    // node builtins stay external automatically on platform:node;
    // workspace packages (@patchstory/*) are bundled from their TS source.
  });
  chmodSync(outfile, 0o755);
  return outfile;
}

async function run() {
  const t0 = Date.now();
  const css = readFileSync(join(webDir, "styles.css"), "utf8");
  const html = readFileSync(join(webDir, "index.html"), "utf8");
  const js = await bundleWebClient();
  generateAssetsModule(js, css, html);
  const cli = await bundleCli();
  const ms = Date.now() - t0;
  process.stdout.write(
    `built in ${ms}ms\n  web client: ${(js.length / 1024).toFixed(1)} KB (minified)\n  cli: ${cli}\n`,
  );
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
